name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Configure:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            build/
            .gradle/
            ~/.gradle/caches
          key: ${{ runner.os }}-build-2-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-build
      - uses: actions/setup-java@v1
        with:
            distribution: 'adopt'
            java-version: '14'
            check-latest: true

      # Test:
      - run: ./gradlew test

      # Publish JAR:
      - run: ./gradlew jar
      - uses: softprops/action-gh-release@v1
        if: "startsWith(github.ref, 'refs/tags/v')"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            build/libs/*.jar
